# -*- coding: utf-8 -*-
"""CIS550DataCleaning

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12C4TXgDm2muwTH1Y63JbCf3VRgea_3-w
"""

pip install -U pandasql

import pandas as pd
from pandasql import sqldf
import datetime
import dateutil.parser
pysqldf = lambda q: sqldf(q, globals())

companies_df = pd.read_excel('/content/drive/My Drive/CIS450Project/Companies.xlsx')
companies_df = companies_df.drop(columns = ['founded_month','founded_quarter'])
print(type(companies_df['founded_at'][0]))

companies_df = companies_df.dropna(subset = ['permalink','name','homepage_url','category_list','market','funding_total_usd','status','country_code',
                                             'region','city','funding_rounds','founded_at','founded_year',
                                             'first_funding_at','last_funding_at'])
companies_df['founded_at'] = companies_df['founded_at'].apply(lambda x:  str(x)[0:10])
companies_df['first_funding_at'] = companies_df['first_funding_at'].apply(lambda x:  str(x)[0:10])
companies_df['last_funding_at'] = companies_df['last_funding_at'].apply(lambda x:  str(x)[0:10])
companies_df = companies_df.drop_duplicates(subset = ['permalink'])
companies_df

rounds_df = pd.read_excel('/content/drive/My Drive/CIS450Project/Rounds.xlsx')
rounds_df = rounds_df.drop(columns = ['company_name','company_category_list','company_market','company_country_code',
                                      'company_state_code','company_region','company_city','funded_month','funded_quarter'])

rounds_df = rounds_df.dropna(subset = ['company_permalink','funding_round_permalink','funding_round_type','funded_at','funded_year','raised_amount_usd'])
rounds_df['funded_at'] = rounds_df['funded_at'].apply(lambda x: str(x)[0:10])
rounds_df = rounds_df.drop_duplicates(subset = ['funding_round_permalink'])
rounds_df

investments_df = pd.read_excel('/content/drive/My Drive/CIS450Project/Investments.xlsx')

investments_df = investments_df.drop(columns = ['company_name', 'company_category_list','company_market',
                                                'company_country_code','company_state_code','company_region',
                                                'company_city','funding_round_type','funding_round_code',
                                                'funded_at','funded_month','funded_quarter','funded_year',
                                                'raised_amount_usd'  ])
investments_df.dropna(subset = ['company_permalink','investor_permalink','funding_round_permalink'])
investments_df = investments_df.drop_duplicates(['investor_permalink'])
investments_df

acquisitions_df = pd.read_excel('/content/drive/My Drive/CIS450Project/Acquisitions.xlsx')
acquisitions_df = acquisitions_df.drop(columns = ['company_name','company_category_list','company_market',
                                                  'company_country_code','company_state_code','company_region',
                                                  'company_city','acquired_month','acquired_quarter'])

acquisitions_df.dropna(subset = ['company_permalink','acquirer_permalink'])
acquisitions_df['acquired_at'] = acquisitions_df['acquired_at'].apply(lambda x: str(x)[0:10])
acquisitions_df = acquisitions_df.drop_duplicates(['acquirer_permalink'])
acquisitions_df

q = """SELECT
        c.name, c.permalink, COUNT(r.funding_round_permalink) AS no_rounds
        FROM companies_df c JOIN rounds_df r ON c.permalink = r.company_permalink
        GROUP BY r.company_permalink
        HAVING COUNT(r.funding_round_permalink) = c.funding_rounds;"""
joined = pysqldf(q)
joined

q3 = """SELECT c.*
        FROM companies_df c JOIN joined j ON j.permalink = c.permalink"""
companies_filtered = pysqldf(q3)
companies_filtered

q4 = """SELECT r.*
        FROM rounds_df r JOIN joined j ON r.company_permalink = j.permalink"""
rounds_filtered = pysqldf(q4)
rounds_filtered

q1 = """SELECT
          i.*
          FROM investments_df i JOIN joined j ON j.permalink = i.company_permalink
          WHERE funding_round_permalink IN (
            SELECT r.funding_round_permalink
            FROM rounds_filtered r
          );"""
          #GROUP BY i.company_permalink;"""
investment_filtered = pysqldf(q1)
investment_filtered

q2 = """SELECT
          a.*
          FROM acquisitions_df a JOIN joined j ON j.permalink = a.company_permalink;"""
          #GROUP BY a.company_permalink;"""
acquisitions_filtered = pysqldf(q2)
acquisitions_filtered

acquisitions_filtered.to_excel(r'AcquisitionsCleaned.xlsx', index = False)